-- Bảng Khách hàng
CREATE TABLE [KhachHang] (
	MaKhach VARCHAR(20) NOT NULL PRIMARY KEY,
	TenKhach NVARCHAR(100) NOT NULL,
	DiaChi NVARCHAR(200) NOT NULL,
	DienThoai VARCHAR(15) NOT NULL
);
GO

-- Bảng Công việc
CREATE TABLE [CongViec] (
	MaCv VARCHAR(20) NOT NULL PRIMARY KEY,
	TenCongViec NVARCHAR(100) NOT NULL
);
GO

-- Bảng Nhà cung cấp
CREATE TABLE [NhaCungCap] (
	MaNCC VARCHAR(20) NOT NULL PRIMARY KEY,
	TenNhaCungCap NVARCHAR(100) NOT NULL,
	DiaChi NVARCHAR(200) NOT NULL,
	DienThoai VARCHAR(15) NOT NULL
);
GO

-- Bảng Ngôn ngữ
CREATE TABLE [NgonNgu] (
	MaNgonNgu VARCHAR(20) NOT NULL PRIMARY KEY,
	TenNgonNgu NVARCHAR(100) NOT NULL
);
GO

-- Bảng Nhà xuất bản
CREATE TABLE [NhaXuatBan] (
	MaNXB VARCHAR(20) NOT NULL PRIMARY KEY,
	TenNXB NVARCHAR(100) NOT NULL,
	SDT CHAR(10) NOT NULL,
	Email VARCHAR(100) NOT NULL,
	DiaChi NVARCHAR(200) NOT NULL
);
GO

-- Bảng Loại sách
CREATE TABLE [LoaiSach] (
	MaLoaiSach VARCHAR(20) NOT NULL PRIMARY KEY,
	TenLoai NVARCHAR(100) NOT NULL
);
GO

-- Bảng Tác giả
CREATE TABLE [TacGia] (
	MaTacGia VARCHAR(20) NOT NULL PRIMARY KEY,
	TenTacGia NVARCHAR(100) NOT NULL,
	NgaySinh DATE NOT NULL,
	GioiTinh NVARCHAR(10) NOT NULL,
	DiaChi NVARCHAR(200) NOT NULL
);
GO

-- Bảng Lĩnh vực
CREATE TABLE [LinhVuc] (
	MaLinhVuc VARCHAR(20) NOT NULL PRIMARY KEY,
	TenLinhVuc NVARCHAR(100) NOT NULL
);
GO

-- Bảng Kho sách
CREATE TABLE [KhoSach] (
	MaSach VARCHAR(20) NOT NULL PRIMARY KEY,
	TenSach NVARCHAR(100) NOT NULL,
	SoLuong INT NOT NULL,
	DonGiaNhap VARCHAR(20) NOT NULL,
	DonGiaBan VARCHAR(20) NOT NULL,
	MaLoaiSach VARCHAR(20) NOT NULL,
	MaTacGia VARCHAR(20) NOT NULL,
	MaNXB VARCHAR(20) NOT NULL,
	MaLinhVuc VARCHAR(20) NOT NULL,
	MaNgonNgu VARCHAR(20) NOT NULL,
	Anh VARCHAR(200) NOT NULL,
	SoTrang INT NOT NULL
);
GO

-- Chỉ mục cho Kho sách
CREATE INDEX IX_KhoSach_MaSach ON KhoSach(MaSach);
GO

-- Bảng Mất sách
CREATE TABLE [MatSach] (
	MaLanMat INT IDENTITY PRIMARY KEY,
	MaSach VARCHAR(20) NOT NULL,
	SLMat INT NOT NULL,
	NgayMat DATE NOT NULL
);
GO

CREATE INDEX IX_MatSach_MaSach ON MatSach(MaSach);
GO

-- Bảng Nhân viên
CREATE TABLE [NhanVien] (
	MaNhanVien VARCHAR(20) NOT NULL PRIMARY KEY,
	TenNhanVien NVARCHAR(100) NOT NULL,
	DienThoai VARCHAR(15) NOT NULL,
	DiaChi NVARCHAR(200) NOT NULL,
	MaCv VARCHAR(20) NOT NULL
);
GO

-- Bảng Hóa đơn nhập
CREATE TABLE [HoaDonNhap] (
	SoHDNhap VARCHAR(20) NOT NULL PRIMARY KEY,
	MaNhanVien VARCHAR(20) NOT NULL,
	NgayNhap DATE NOT NULL,
	MaNCC VARCHAR(20) NOT NULL,
	TongTien FLOAT NOT NULL
);
GO

-- Bảng Chi tiết hóa đơn nhập
CREATE TABLE [ChiTietHDNhap] (
	SoHDNhap VARCHAR(20) NOT NULL,
	MaSach VARCHAR(20) NOT NULL,
	SLNhap INT NOT NULL,
	DonGiaNhap FLOAT NOT NULL,
	KhuyenMai FLOAT NOT NULL,
	ThanhTien FLOAT NOT NULL,
	PRIMARY KEY (SoHDNhap, MaSach)
);
GO

-- Bảng Hóa đơn bán
CREATE TABLE [HoaDonBan] (
	SoHDBan VARCHAR(20) NOT NULL PRIMARY KEY,
	MaNhanVien VARCHAR(20) NOT NULL,
	NgayBan DATE NOT NULL,
	MaKhach VARCHAR(20) NOT NULL,
	TongTien FLOAT NOT NULL
);
GO

-- Bảng Chi tiết hóa đơn bán
CREATE TABLE [ChiTietHDBan] (
	SoHDBan VARCHAR(20) NOT NULL,
	MaSach VARCHAR(20) NOT NULL,
	SLBan INT NOT NULL,
	KhuyenMai FLOAT NOT NULL,
	ThanhTien FLOAT NOT NULL,
	PRIMARY KEY (SoHDBan, MaSach)
);
GO

-- RÀNG BUỘC KHOÁ NGOẠI
ALTER TABLE KhoSach
	ADD FOREIGN KEY (MaLoaiSach) REFERENCES LoaiSach(MaLoaiSach),
		FOREIGN KEY (MaTacGia) REFERENCES TacGia(MaTacGia),
		FOREIGN KEY (MaNXB) REFERENCES NhaXuatBan(MaNXB),
		FOREIGN KEY (MaLinhVuc) REFERENCES LinhVuc(MaLinhVuc),
		FOREIGN KEY (MaNgonNgu) REFERENCES NgonNgu(MaNgonNgu);
GO

ALTER TABLE MatSach
	ADD FOREIGN KEY (MaSach) REFERENCES KhoSach(MaSach);
GO

ALTER TABLE NhanVien
	ADD FOREIGN KEY (MaCv) REFERENCES CongViec(MaCv);
GO

ALTER TABLE HoaDonNhap
	ADD FOREIGN KEY (MaNhanVien) REFERENCES NhanVien(MaNhanVien),
		FOREIGN KEY (MaNCC) REFERENCES NhaCungCap(MaNCC);
GO

ALTER TABLE ChiTietHDNhap
	ADD FOREIGN KEY (SoHDNhap) REFERENCES HoaDonNhap(SoHDNhap),
		FOREIGN KEY (MaSach) REFERENCES KhoSach(MaSach);
GO

ALTER TABLE HoaDonBan
	ADD FOREIGN KEY (MaNhanVien) REFERENCES NhanVien(MaNhanVien),
		FOREIGN KEY (MaKhach) REFERENCES KhachHang(MaKhach);
GO

ALTER TABLE ChiTietHDBan
	ADD FOREIGN KEY (SoHDBan) REFERENCES HoaDonBan(SoHDBan),
		FOREIGN KEY (MaSach) REFERENCES KhoSach(MaSach);
GO
CREATE TABLE [TaiKhoan] (
	usename VARCHAR(20) NOT NULL,
	password VARCHAR(20) NOT NULL,
	PhanQuyen int NOT NULL,
	
);